---
  - name: TASK 1 - ENSURE SERVER OBJECTS ARE DEPLOYED
    netscaler_server:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      server_name: "{{ item.name }}"
      ip_address: "{{ item.ip_address }}"
      comment: "{{ item.comment | default('') }}"
      partition: "{{ partition | default('') }}"
    with_items: "{{ servers }}"

  - name: TASK 2 - ENSURE SERVICE GROUPS ARE DEPLOYED
    netscaler_servicegroup:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      servicegroup_name: "{{ item.name }}"
      service_type: "{{ item.service_type }}"
      comment: "{{ item.comment | default('') }}"
      partition: "{{ partition | default('') }}"
    with_items: "{{ service_groups }}"

  - name: TASK 3 - ENSURE CS VSERVERS ARE DEPLOYED
    netscaler_csvserver:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      backup_csvserver: "{{ item.backup_vserver | default('') }}"
      csvserver_name: "{{ item.name }}"
      ip_address: "{{ item.ip_address }}"
      service_type: "{{ item.service_type | default('') }}"
      csvserver_port: "{{ item.port | default('') }}"
      #lbmethod: "{{ item.lb_method | default('LEASTCONNECTION') }}"
      #persistence: "{{ item.persistence | default('') }}"
      #conn_failover: "{{ item.conn_failover | default('DISABLED') }}"
      comment: "{{ item.comment | default('') }}"
      #partition: "{{ partition | default('') }}"
    with_items: "{{ cs_vservers }}"

  - name: TASK 4 - ENSURE LB VSERVERS ARE DEPLOYED
    netscaler_lbvserver:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      #backup_lbvserver: "{{ item.backup_vserver | default('') }}"
      lbvserver_name: "{{ item.name }}"
      ip_address: "{{ item.ip_address }}"
      service_type: "{{ item.service_type }}"
      lbvserver_port: "{{ item.port | default('') }}"
      lbmethod: "{{ item.lb_method | default('LEASTCONNECTION') }}"
      #persistence: "{{ item.persistence | default('') }}"
      #conn_failover: "{{ item.conn_failover | default('DISABLED') }}"
      comment: "{{ item.comment | default('') }}"
      partition: "{{ partition | default('') }}"
    with_items: "{{ lb_vservers }}"

  - name: TASK 5 - ENSURE MONITORS ARE DEPLOYED
    netscaler_lbmonitor:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      monitor_name: "{{ item.name }}"
      monitor_type: "{{ item.type }}"
      http_request: "{{ item.request | default('') }}"
      monitor_use_ssl: "{{ item.secure | default('NO') }}"
      response_code: "{{ item.response_code | default([]) }}"
      partition: "{{ partition | default('') }}"
    when: monitors is defined
    with_items: "{{ monitors }}"

  - name: TASK 6 - ENSURE SERVICEGROUPS ARE BOUND TO SERVERS
    netscaler_servicegroup_server:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      servicegroup_name: "{{ item.servicegroup_name }}"
      server_name: "{{ item.server_name }}"
      server_port: "{{ item.port }}"
      #partition: "{{ partition | default('') }}"
    with_items: "{{ bindings.servicegroup_to_servers }}"

  - name: TASK 7 - ENSURE LB VSEVERS ARE BOUND TO SERVICEGROUPS
    netscaler_lbvserver_servicegroup:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      lbvserver_name: "{{ item.vserver_name }}"
      servicegroup_name: "{{ item.servicegroup_name }}"
      #partition: "{{ partition | default('') }}"
    with_items: "{{ bindings.lbvserver_to_servicegroup }}"

  - name: TASK 8 - ENSURE CS VSEVERS ARE BOUND TO LBVSERVERS
    netscaler_csvserver_lbvserver_binding:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      csvserver_name: "{{ item.name }}"
      lbvserver_name: "{{ item.lbvserver }}"
      #partition: "{{ partition | default('') }}"
    with_items: "{{ bindings.lbvserver_to_csvserver }}"

  - name: TASK 9 - ENSURE CS VSEVERS ARE BOUND TO SSLCERTKEY
    netscaler_sslvserver_sslcertkey_binding:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      certkeyname: "{{ item.certkeyname }}"
      vservername: "{{ item.vservername }}"
    with_items: "{{ bindings.sslcertkey_to_vservername }}"

  - name: TASK 10 - ENSURE CS VSEVERS ARE BOUND TO SSLCIPHERSUITE
    netscaler_sslvserver_sslciphersuite_binding:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      vservername: "{{ item.vservername }}"
      ciphername: "{{ item.ciphername }}"
    with_items: "{{ bindings.sslciphersuite_to_vservername }}"

  - name: TASK 11 - ENSURE CS VSEVERS ARE BOUND TO RESPONDERPOLICIES
    netscaler_csvserver_responderpolicy_binding:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      csvserver_name: "{{ item.name }}"
      rp_name: "{{ item.policyname }}"
      rp_priority: "{{ item.priority }}"
      rp_gotopriorityexpression: "{{ item.gotopriorityexpression }}"
      #rp_bindpoint: "{{ item.bindpoint }}"
      #rp_targetlbvserver: "{{ item.targetlbvserver }}"
      #partition: "{{ partition | default('') }}"
    with_items: "{{ bindings.responderpolicies_to_csvserver }}"

  - name: TASK 12 - ENSURE CS VSEVERS ARE BOUND TO REWRITEPOLICIES
    netscaler_csvserver_rewritepolicy_binding:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      csvserver_name: "{{ item.name }}"
      rp_name: "{{ item.policyname }}"
      rp_priority: "{{ item.priority }}"
      rp_gotopriorityexpression: "{{ item.gotopriorityexpression }}"
      rp_bindpoint: "{{ item.bindpoint }}"
      #rp_targetlbvserver: "{{ item.targetlbvserver }}"
      #partition: "{{ partition | default('') }}"
    with_items: "{{ bindings.rewritepolicies_to_csvserver }}"

  - name: TASK 13 - ENSURE SERVICEGROUPS ARE BOUND TO MONITORS
    netscaler_servicegroup_monitor:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      servicegroup_name: "{{ item.servicegroup_name }}"
      monitor_name: "{{ item.monitor_name }}"
      partition: "{{ partition | default('') }}"
    with_items: "{{ bindings.servicegroup_to_monitors }}"

  - name: TASK 14 - ENSURE SSL VSERVERS ARE DEPLOYED WITHOUT WEAK PROTOCOLS
    netscaler_sslvserver:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "{{ item.state | default('present') }}"
      vservername: "{{ item.vservername }}"
      ssl3: "{{ item.ssl3 }}"
      tls1: "{{ item.tls1 }}"
      #tls11: "{{ item.tls11 }}"
      #tls12: "{{ item.tls12 }}"
      #ocspstapling: "{{ item.ocspstapling }}"
      #clientauth: "{{ item.clientauth }}"
      #clientcert: "{{ item.clientcert }}"
    with_items: "{{ ssl_vservers }}"
